spring:
  config:
    activate:
      on-profile: dev
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-management-service
          uri: http://localhost:8000/
          predicates:
            - Path=/auth/**, /oauth2/**, /user/**
        - id: tenant-management-service
          uri: http://localhost:8001/
          predicates:
            - Path=/tenant/**
        - id: product-management-service
          uri: http://localhost:8002/
          predicates:
            - Path=/product/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  config:
    activate:
      on-profile: test
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-management-service-test
          uri: https://kaguvi-user-management-service.herokuapp.com/
          predicates:
            - Path=/auth/**, /oauth2/**
        - id: tenant-management-service
          uri: https://kaguvi-tenant-management-svc.herokuapp.com/
          predicates:
            - Path=/tenant/**
        - id: product-management-service
          uri: https://kaguvi-product-management.herokuapp.com/
          predicates:
            - Path=/product/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: https://kaguvi-service-registry.herokuapp.com/eureka/