spring:
  config:
    activate:
      on-profile: dev
  application:
    name: api-gateway-dev
  cloud:
    gateway:
      routes:
        - id: user-management-service
          uri: http://localhost:8000/
          predicates:
            - Path=/auth/**, /oauth2/**
        - id: consumerModule
          uri: http://localhost:8082/
          predicates:
            - Path=/consumer/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  config:
    activate:
      on-profile: test
  application:
    name: api-gateway-test
  cloud:
    gateway:
      routes:
        - id: user-management-service-test
          uri: https://kaguvi-user-management-service.herokuapp.com/
          predicates:
            - Path=/auth/**, /oauth2/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: https://kaguvi-service-registry.herokuapp.com/eureka/